version: '3.1'

services:
  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgresContainer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - '5432:5432'